from typing import Optional, Set, List, Tuple

class RustBlock:
    @property
    def id(self) -> int: ...

    @property
    def height(self) -> int: ...

    @property
    def hash(self) -> bytes: ...

    @property
    def parent_hash(self) -> Optional[bytes]: ...

    @property
    def referee_hashes(self) -> Set[bytes]: ...

    @property
    def timestamp(self) -> int: ...

    @property
    def log_timestamp(self) -> int: ...

    @property
    def tx_count(self) -> int: ...

    @property
    def block_size(self) -> int: ...

    @property
    def children(self) -> List[bytes]: ...

    @property
    def epoch_block(self) -> Optional[bytes]: ...

    @property
    def epoch_set(self) -> Set[int]: ...

    @property
    def past_set_size(self) -> int: ...

    @property
    def subtree_size(self) -> int: ...
    
    @property
    def epoch_size(self) -> int: ...
    
class RustGraph:
    @staticmethod
    def load(path: str) -> RustGraph: ...
    
    @property
    def pivot_chain(self) -> List[RustBlock]: ...
    
    def epoch_span(self, block: RustBlock) -> int: ...
    
    def avg_epoch_time(self, block: RustBlock) -> float: ...
    
    def confirmation_risk(self, block: RustBlock, adv_percent: int, risk_threshold: float) -> Tuple[int, int, int, float]: ...
    
    def avg_confirm_time(self, adv_percent: int, risk_threshold: float) -> Tuple[float, int]: ...